Updated the copy in the README files
komodorio/komodor-tutorials pull request #19
Opened 2023-01-19 16:41 UTC by hughbrien

Just did some edits to the copy in the README files 
Added an Agent installation script

2023-01-19 17:22 UTC, guymenahem requested changes

2023-01-19 17:22 UTC, guymenahem commented on install-agent.sh
> +#!/bin/sh
I think it's better to keep the installation command in the product.
There are always changes to values and it will be hard to maintain.

2023-01-20 08:12 UTC, guymenahem approved these changes

2023-01-20 08:13 UTC, guymenahem commented on install-agent.sh
> +#!/bin/sh
Resolved

2023-01-20 16:03 UTC, hughbrien commented
First Fork and merge

2023-01-20 16:06 UTC, merged